'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices
<Assembly: ComVisibleAttribute(false),  _
 Assembly: CLSCompliantAttribute(false),  _
 Assembly: AssemblyVersionAttribute("1.3.3.7"),  _
 Assembly: AssemblyFileVersionAttribute("1.3.3.7"),  _
 Assembly: AssemblyCopyrightAttribute("Copyright (c) 2015, kCura Corporation."),  _
 Assembly: AssemblyTitleAttribute("BuildTools"),  _
 Assembly: AssemblyDescriptionAttribute("Tools to help build source code for kCura repositories."),  _
 Assembly: AssemblyCompanyAttribute("kCura Corporation"),  _
 Assembly: AssemblyProductAttribute("BuildTools")> 

