'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices
<Assembly: ComVisibleAttribute(false),  _
 Assembly: CLSCompliantAttribute(false),  _
 Assembly: AssemblyVersionAttribute("1.0.0.0"),  _
 Assembly: AssemblyFileVersionAttribute("1.0.0.0"),  _
 Assembly: AssemblyInformationalVersionAttribute("1.0.0.0-default-dev-local"),  _
 Assembly: AssemblyCopyrightAttribute("Copyright (c) 2015, kCura LLC"),  _
 Assembly: AssemblyTitleAttribute("Template"),  _
 Assembly: AssemblyDescriptionAttribute("Template Description"),  _
 Assembly: AssemblyCompanyAttribute("kCura LLC"),  _
 Assembly: AssemblyProductAttribute("Template")> 

