trigger:
  branches:
    include:
    - '*'

variables:
- name: unregister.opt-in
  value: true
  DisableNuGetWarning: 'NU1604'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    msbuildArguments: '/p:NoWarn=$(DisableNuGetWarning)'

resources:
  repositories:
    - repository: azdo_templates
      type: github
      name: relativityone/azdo-templates
      endpoint: relativityone
      ref: 'refs/heads/main'

stages:
- template: rapci-server.yml@azdo_templates  # Template reference
  parameters:
    RelativityBranch: ''
    TemplateName: 'aio-server-2023-ga'
    buildSteps:
      - checkout: self
      - checkout: azdo_templates