trigger:
  branches:
    include:
    - '*'

variables:
- name: unregister.opt-in
  value: true

resources:
  repositories:
    - repository: azdo_templates
      type: github
      name: relativityone/azdo-templates
      endpoint: relativityone
      ref: 'refs/heads/main'

stages:
- template: rapci-server.yml@azdo_templates  # Template reference
  parameters:
    RelativityBranch: 'release-12.3-2023-patch2'
    TemplateName: 'aio-server-2023-ga'
    DeployHotfixOrPatch: true
    buildSteps:
      - checkout: self
      - checkout: azdo_templates