//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kCura.IntegrationPoints.Services.RelativityWebApi {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kCura.com/EDDS/RelativityManager", ConfigurationName="RelativityWebApi.RelativityManagerSoap")]
    public interface RelativityManagerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/RetrieveCurrencySymbol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RetrieveCurrencySymbol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/RetrieveCurrencySymbol", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RetrieveCurrencySymbolAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/RetrieveRelativityVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RetrieveRelativityVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/RetrieveRelativityVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RetrieveRelativityVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/ValidateSuccessfulLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidateSuccessfulLogin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/ValidateSuccessfulLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ValidateSuccessfulLoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/GetServerTimezoneOffset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetServerTimezoneOffset();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/GetServerTimezoneOffset", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetServerTimezoneOffsetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/IsAuditingEnabled", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsAuditingEnabled();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/IsAuditingEnabled", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsAuditingEnabledAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/IsImportEmailNotificationEnabled", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsImportEmailNotificationEnabled();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/IsImportEmailNotificationEnabled", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsImportEmailNotificationEnabledAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/RetrieveRdcConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RetrieveRdcConfiguration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/RetrieveRdcConfiguration", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RetrieveRdcConfigurationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/ReceiveText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ReceiveText(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/ReceiveText", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ReceiveTextAsync(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/GetInstanceInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetInstanceInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/GetInstanceInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetInstanceInformationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/GetRelativityUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRelativityUrl();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kCura.com/EDDS/RelativityManager/GetRelativityUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetRelativityUrlAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RelativityManagerSoapChannel : kCura.IntegrationPoints.Services.RelativityWebApi.RelativityManagerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RelativityManagerSoapClient : System.ServiceModel.ClientBase<kCura.IntegrationPoints.Services.RelativityWebApi.RelativityManagerSoap>, kCura.IntegrationPoints.Services.RelativityWebApi.RelativityManagerSoap {
        
        public RelativityManagerSoapClient() {
        }
        
        public RelativityManagerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RelativityManagerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RelativityManagerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RelativityManagerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RetrieveCurrencySymbol() {
            return base.Channel.RetrieveCurrencySymbol();
        }
        
        public System.Threading.Tasks.Task<string> RetrieveCurrencySymbolAsync() {
            return base.Channel.RetrieveCurrencySymbolAsync();
        }
        
        public string RetrieveRelativityVersion() {
            return base.Channel.RetrieveRelativityVersion();
        }
        
        public System.Threading.Tasks.Task<string> RetrieveRelativityVersionAsync() {
            return base.Channel.RetrieveRelativityVersionAsync();
        }
        
        public bool ValidateSuccessfulLogin() {
            return base.Channel.ValidateSuccessfulLogin();
        }
        
        public System.Threading.Tasks.Task<bool> ValidateSuccessfulLoginAsync() {
            return base.Channel.ValidateSuccessfulLoginAsync();
        }
        
        public int GetServerTimezoneOffset() {
            return base.Channel.GetServerTimezoneOffset();
        }
        
        public System.Threading.Tasks.Task<int> GetServerTimezoneOffsetAsync() {
            return base.Channel.GetServerTimezoneOffsetAsync();
        }
        
        public bool IsAuditingEnabled() {
            return base.Channel.IsAuditingEnabled();
        }
        
        public System.Threading.Tasks.Task<bool> IsAuditingEnabledAsync() {
            return base.Channel.IsAuditingEnabledAsync();
        }
        
        public bool IsImportEmailNotificationEnabled() {
            return base.Channel.IsImportEmailNotificationEnabled();
        }
        
        public System.Threading.Tasks.Task<bool> IsImportEmailNotificationEnabledAsync() {
            return base.Channel.IsImportEmailNotificationEnabledAsync();
        }
        
        public System.Data.DataSet RetrieveRdcConfiguration() {
            return base.Channel.RetrieveRdcConfiguration();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RetrieveRdcConfigurationAsync() {
            return base.Channel.RetrieveRdcConfigurationAsync();
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<string> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public bool ReceiveText(string text) {
            return base.Channel.ReceiveText(text);
        }
        
        public System.Threading.Tasks.Task<bool> ReceiveTextAsync(string text) {
            return base.Channel.ReceiveTextAsync(text);
        }
        
        public string GetInstanceInformation() {
            return base.Channel.GetInstanceInformation();
        }
        
        public System.Threading.Tasks.Task<string> GetInstanceInformationAsync() {
            return base.Channel.GetInstanceInformationAsync();
        }
        
        public string GetRelativityUrl() {
            return base.Channel.GetRelativityUrl();
        }
        
        public System.Threading.Tasks.Task<string> GetRelativityUrlAsync() {
            return base.Channel.GetRelativityUrlAsync();
        }
    }
}
