@startuml
skinparam activity {
 BackgroundColor<< Error >> #ff6666
}

(*) --> "Agent initializes ExportServiceManager"
partition JobPreExecute {
 --> "Create/Retrieve JobHistory"
 --> "Create StopJobManager"
 --> "Bind StopJobManager with the job history and the scheduled agent job"
 --> "Pass StopJobManager to IJobHistoryErrorService"
 if "Check if the job is in stopping state." then
	--> [true] FinalizeExportService
 else
   --> [false] InitializeExporter
 endif
}

partition InitializeExporter {
  --> "Initialize the Exporter"
  if "StopJobManager received the stop signal" then
      --> FinalizeExportService
  else
	 --> [false] "Hand off the stop token to the data reader."
     --> "Read data"
	 if "there is data to push to the IAPI" then
     	if "StopJobManager received the stop signal" then
      		--> FinalizeExportService 
     	else
     	    --> "Read data"
		endif
	else 
       --> FinalizeExportService 
	endif
  endif
}
 
partition FinalizeExportService {
	--> "Tag documents"
    --> "Clean up scratch tables if any"
    --> "Update Job History error to expired"
    --> "Update job's stop state back to 'None', if the current job is a scheduled job."
    --> (*)
}

@enduml