 @startuml
skinparam activity {
 BackgroundColor<< Error >> #ff6666
}

(*) --> "Agent initializes SyncWorker"
partition Initialization {
 --> "Create/Retrieve JobHistory"
 --> "Create StopJobManager"
 --> "Bind the StopJobManager with the job history and the scheduled agent job"
 --> "Pass the StopJobManager to IJobHistoryErrorService"
}
partition Pushing data{
  if "StopJobManager receive the stopping signal" then
      --> Finalize the job
  else
	 --> [false] "Hand off the stopping token to the data synchronizer."
     --> "Read data"
	 if "there are data to push to the IAPI" then
     	if "the StopJobManager receive the stopping signal" then
      		--> Finalize the job
     	else
			--> "Push the data into the import service."
     	    --> "Read data"
		endif
	else 
       --> Finalize the job
	endif
  endif
}
 
partition FinalizeJob{
   if "the job has been canceled and this is the last batch" then 
	 --> "Update the job history status to be 'Canceled' "
   else
     --> "Update the job history status to be an appropriate status. "
   endif
   --> (*)
}

@enduml