	 @startuml
skinparam activity {
 BackgroundColor<< Error >> #ff6666
}

(*) --> "Agent initializes SyncManager"
partition JobPreExecute {
 --> "Create/Retrieve JobHistory"
 --> "Create StopJobManager"
 --> "Bind StopJobManager with the job history and the scheduled agent job"
 --> "Pass StopJobManager to IJobHistoryErrorService"
 if "Check if the job is in stopping state." then
	--> [true] JobPostExecute 
 else
   --> [false] BatchTask 
 endif
}

partition BatchTask {
if "There is an id to be batched out"  then
	--> [true] "Check StopJobManager if the stopping is requested."
	if "The stopping is signaled" then
		--> [true] JobPostExecute
	else
		--> [false] "Read ids from the source provider"
		--> "Add batch id into the batch collection"
        --> "Check StopJobManager if the stopping is requested."
	end if
else 
  --> JobPostExecute
endif
}

partition JobPostExecute {
--> "Update job's stop state back to 'None', if the current job is a scheduled job."
if "There is no child job created" then
	--> [true] "Update the job history's status to stopped."
	--> (*)
else 
	--> [false] (*)
endif
}
 
@enduml