// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace kCura.IntegrationPoints.Core.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JobStatusMessages {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobStatusMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kCura.IntegrationPoints.Core.Properties.JobStatusMessages", typeof(JobStatusMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A Job for the following Relativity Integration Point has successfully completed.
        ///
        ///Name: [RIP.Name]
        ///[RIP.SOURCEEMAILBODYDATA]
        ///[RIP.DESTINATIONEMAILBODYDATA].
        /// </summary>
        internal static string JOB_COMPLETED_SUCCESS_BODY {
            get {
                return ResourceManager.GetString("JOB_COMPLETED_SUCCESS_BODY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relativity Job successfully completed for &quot;[RIP.Name]&quot;..
        /// </summary>
        internal static string JOB_COMPLETED_SUCCESS_SUBJECT {
            get {
                return ResourceManager.GetString("JOB_COMPLETED_SUCCESS_SUBJECT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error has occurred for the below Relativity Integration Point.
        ///
        ///Name: [RIP.Name]
        ///[RIP.SOURCEEMAILBODYDATA]
        ///[RIP.DESTINATIONEMAILBODYDATA]
        ///
        ///For error details, please review job history errors for this integration point..
        /// </summary>
        internal static string JOB_COMPLETED_WITH_ERRORS_BODY {
            get {
                return ResourceManager.GetString("JOB_COMPLETED_WITH_ERRORS_BODY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relativity Job completed with errors for &quot;[RIP.NAME]&quot;..
        /// </summary>
        internal static string JOB_COMPLETED_WITH_ERRORS_SUBJECT {
            get {
                return ResourceManager.GetString("JOB_COMPLETED_WITH_ERRORS_SUBJECT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error has occurred for the below Relativity Integration Point.
        ///
        ///Name: [RIP.NAME]
        ///[RIP.SOURCEEMAILBODYDATA]
        ///[RIP.DESTINATIONEMAILBODYDATA]
        ///
        ///Error: [Error].
        /// </summary>
        internal static string JOB_FAILED_BODY {
            get {
                return ResourceManager.GetString("JOB_FAILED_BODY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relativity Job completed with errors for &quot;[RIP.NAME]&quot;..
        /// </summary>
        internal static string JOB_FAILED_SUBJECT {
            get {
                return ResourceManager.GetString("JOB_FAILED_SUBJECT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A Job for the following Relativity Integration Point has successfully stopped.
        ///
        ///Name: [RIP.Name]
        ///
        ///[RIP.SOURCEEMAILBODYDATA]
        ///[RIP.DESTINATIONEMAILBODYDATA].
        /// </summary>
        internal static string JOB_STOPPED_BODY {
            get {
                return ResourceManager.GetString("JOB_STOPPED_BODY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relativity Job successfully stopped for &quot;[RIP.NAME]&quot;..
        /// </summary>
        internal static string JOB_STOPPED_SUBJECT {
            get {
                return ResourceManager.GetString("JOB_STOPPED_SUBJECT", resourceCulture);
            }
        }
    }
}
