// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

#pragma warning disable RG2001 // Character Per Line

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Authentication.OAuth2ClientFactory.GetOauth2ClientAsync(System.Int32)~System.Threading.Tasks.Task{Relativity.Services.Security.Models.OAuth2Client}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.DataSourceSnapshotExecutor.ExecuteAsync(Relativity.Sync.Configuration.IDataSourceSnapshotConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.ExecutionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.DestinationWorkspaceSavedSearchCreationExecutor.ExecuteAsync(Relativity.Sync.Configuration.IDestinationWorkspaceSavedSearchCreationConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.ExecutionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.DestinationWorkspaceTagLinker.LinkDestinationWorkspaceTagToJobHistoryAsync(System.Int32,System.Int32,System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.DestinationWorkspaceTagRepository.QueryRelativityObjectTagAsync(System.Int32,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Services.Objects.DataContracts.RelativityObject}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.DestinationWorkspaceTagRepository.CreateAsync(System.Int32,System.Int32,System.String)~System.Threading.Tasks.Task{Relativity.Sync.Executors.DestinationWorkspaceTag}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.DestinationWorkspaceTagRepository.UpdateAsync(System.Int32,Relativity.Sync.Executors.DestinationWorkspaceTag)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.TagSavedSearch.CreateTagSavedSearchAsync(Relativity.Sync.Configuration.IDestinationWorkspaceSavedSearchCreationConfiguration,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.Validation.FieldMappingsValidator.ValidateAsync(Relativity.Sync.Configuration.IValidationConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.Executors.Validation.ValidationResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.RelativitySourceCaseTagRepository.QueryRelativityObjectTagAsync(System.Int32,System.Int32,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Services.Objects.DataContracts.RelativityObject}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.RelativitySourceCaseTagRepository.CreateAsync(System.Int32,Relativity.Sync.Executors.RelativitySourceCaseTag)~System.Threading.Tasks.Task{Relativity.Sync.Executors.RelativitySourceCaseTag}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.RelativitySourceCaseTagRepository.UpdateAsync(System.Int32,Relativity.Sync.Executors.RelativitySourceCaseTag)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.RelativitySourceJobTagRepository.CreateAsync(System.Int32,Relativity.Sync.Executors.RelativitySourceJobTag,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.Executors.RelativitySourceJobTag}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.SnapshotPartitionExecutor.ExecuteAsync(Relativity.Sync.Configuration.ISnapshotPartitionConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.ExecutionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.SourceWorkspaceTagsCreationExecutor.ExecuteAsync(Relativity.Sync.Configuration.ISourceWorkspaceTagsCreationConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.ExecutionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.TagSavedSearchFolder.CreateSearchContainerInRootAsync(System.Int32)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.Validation.DestinationFolderValidator.ValidateAsync(Relativity.Sync.Configuration.IValidationConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.Executors.Validation.ValidationResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.Validation.DestinationWorkspaceNameValidator.ValidateAsync(Relativity.Sync.Configuration.IValidationConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.Executors.Validation.ValidationResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.Validation.EmailValidator.ValidateAsync(Relativity.Sync.Configuration.IValidationConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.Executors.Validation.ValidationResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.Validation.FolderStructureBehaviorValidator.ValidateAsync(Relativity.Sync.Configuration.IValidationConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.Executors.Validation.ValidationResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.Validation.SavedSearchValidator.ValidateAsync(Relativity.Sync.Configuration.IValidationConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.Executors.Validation.ValidationResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.Validation.SourceWorkspaceNameValidator.ValidateAsync(Relativity.Sync.Configuration.IValidationConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.Executors.Validation.ValidationResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.Validation.ValidationExecutor.ExecuteAsync(Relativity.Sync.Configuration.IValidationConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.ExecutionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.KeplerFactory.KeplerServiceInterceptor.Intercept(SexyProxy.Invocation)~System.Threading.Tasks.Task{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Nodes.SyncNode`1.PerformExecuteAsync(Banzai.IExecutionContext{Relativity.Sync.SyncExecutionContext})~System.Threading.Tasks.Task{Banzai.NodeResultStatus}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.SafeProgressWrapper`1.Report(`0)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Executors.DestinationWorkspaceTagsCreationExecutor.ExecuteAsync(Relativity.Sync.Configuration.IDestinationWorkspaceTagsCreationConfiguration,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Relativity.Sync.ExecutionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.SyncJob.ExecuteAsync(System.Threading.CancellationToken,System.IProgress{Relativity.Sync.SyncJobState}[])~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.SyncJobInLifetimeScope.CreateSyncJob(Autofac.ILifetimeScope)~Relativity.Sync.ISyncJob")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.SyncJobProgress.ReportAsync(Relativity.Sync.SyncJobState)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Relativity.Sync.Telemetry.EnvironmentPropertyProvider.CreateAsync(Relativity.API.IServicesMgr,Relativity.Sync.ISyncLog)~System.Threading.Tasks.Task{Relativity.Sync.Telemetry.IEnvironmentPropertyProvider}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Updating batch progress should never cause failure", Scope = "member", Target = "~M:Relativity.Sync.BatchProgressUpdater.UpdateProgressAsync(Relativity.Sync.Storage.IBatch,System.Int32,System.Int32)~System.Threading.Tasks.Task")]

#pragma warning restore RG2001 // Character Per Line