'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace kCura.EDDS.WebAPI.FieldManagerBase
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FieldManagerSoap", [Namespace]:="http://www.kCura.com/EDDS/FieldManager"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Artifact))>  _
    Partial Public Class FieldManager
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CreateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/RelativityWebApi/FieldManager.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreateCompleted As CreateCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadCompleted As ReadCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kCura.com/EDDS/FieldManager/Create", RequestNamespace:="http://www.kCura.com/EDDS/FieldManager", ResponseNamespace:="http://www.kCura.com/EDDS/FieldManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Create(ByVal caseContextArtifactID As Integer, ByVal fieldDTO As Field) As Integer
            Dim results() As Object = Me.Invoke("Create", New Object() {caseContextArtifactID, fieldDTO})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginCreate(ByVal caseContextArtifactID As Integer, ByVal fieldDTO As Field, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Create", New Object() {caseContextArtifactID, fieldDTO}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreate(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal caseContextArtifactID As Integer, ByVal fieldDTO As Field)
            Me.CreateAsync(caseContextArtifactID, fieldDTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal caseContextArtifactID As Integer, ByVal fieldDTO As Field, ByVal userState As Object)
            If (Me.CreateOperationCompleted Is Nothing) Then
                Me.CreateOperationCompleted = AddressOf Me.OnCreateOperationCompleted
            End If
            Me.InvokeAsync("Create", New Object() {caseContextArtifactID, fieldDTO}, Me.CreateOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateCompleted(Me, New CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kCura.com/EDDS/FieldManager/Read", RequestNamespace:="http://www.kCura.com/EDDS/FieldManager", ResponseNamespace:="http://www.kCura.com/EDDS/FieldManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Read(ByVal caseContextArtifactID As Integer, ByVal fieldArtifactID As Integer) As Field
            Dim results() As Object = Me.Invoke("Read", New Object() {caseContextArtifactID, fieldArtifactID})
            Return CType(results(0),Field)
        End Function
        
        '''<remarks/>
        Public Function BeginRead(ByVal caseContextArtifactID As Integer, ByVal fieldArtifactID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Read", New Object() {caseContextArtifactID, fieldArtifactID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRead(ByVal asyncResult As System.IAsyncResult) As Field
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Field)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal caseContextArtifactID As Integer, ByVal fieldArtifactID As Integer)
            Me.ReadAsync(caseContextArtifactID, fieldArtifactID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal caseContextArtifactID As Integer, ByVal fieldArtifactID As Integer, ByVal userState As Object)
            If (Me.ReadOperationCompleted Is Nothing) Then
                Me.ReadOperationCompleted = AddressOf Me.OnReadOperationCompleted
            End If
            Me.InvokeAsync("Read", New Object() {caseContextArtifactID, fieldArtifactID}, Me.ReadOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadCompleted(Me, New ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/FieldManager")>  _
    Partial Public Class Field
        Inherits Artifact
        
        Private fieldArtifactTypeIDField As Integer
        
        Private displayNameField As String
        
        Private fieldTypeIDField As Integer
        
        Private fieldTypeField As FieldType
        
        Private fieldCategoryIDField As Integer
        
        Private fieldCategoryField As FieldCategory
        
        Private artifactViewFieldIDField As Integer
        
        Private codeTypeIDField As System.Nullable(Of Integer)
        
        Private maxLengthField As System.Nullable(Of Integer)
        
        Private isRequiredField As Boolean
        
        Private isRemovableField As Boolean
        
        Private isEditableField As Boolean
        
        Private isVisibleField As Boolean
        
        Private isArtifactBaseFieldField As Boolean
        
        Private valueField As Object
        
        Private tableNameField As String
        
        Private columnNameField As String
        
        Private isReadOnlyInLayoutField As Boolean
        
        Private filterTypeField As String
        
        Private fieldDisplayTypeIDField As Integer
        
        Private rowsField As Integer
        
        Private isLinkedField As Boolean
        
        Private formatStringField As String
        
        Private repeatColumnField As System.Nullable(Of Integer)
        
        Private associativeArtifactTypeIDField As System.Nullable(Of Integer)
        
        Private isAvailableToAssociativeObjectsField As Boolean
        
        Private isAvailableInChoiceTreeField As Boolean
        
        Private isGroupByEnabledField As Boolean
        
        Private isIndexEnabledField As Boolean
        
        Private displayValueTrueField As String
        
        Private displayValueFalseField As String
        
        Private widthField As String
        
        Private wrappingField As Boolean
        
        Private linkLayoutArtifactIDField As Integer
        
        Private nameValueField As String
        
        Private linkTypeField As Boolean
        
        Private useUnicodeEncodingField As Boolean
        
        Private allowHtmlField As Boolean
        
        Private isSortableField As Boolean
        
        Private friendlyNameField As String
        
        Private importBehaviorField As System.Nullable(Of ImportBehaviorChoice)
        
        Private enableDataGridField As Boolean
        
        Private overlayBehaviorField As System.Nullable(Of Boolean)
        
        Private relationalIndexViewArtifactIDField As System.Nullable(Of Integer)
        
        Private objectsFieldArgsField As ObjectsFieldParameters
        
        Private allowGroupByField As Boolean
        
        Private allowPivotField As Boolean
        
        Private popupPickerViewField As System.Nullable(Of Integer)
        
        Private fieldTreeViewField As System.Nullable(Of Integer)
        
        Private keyboardShortcutField As KeyboardShortcut
        
        Private availableInViewerField As Boolean
        
        Private relativityApplicationsField() As Integer
        
        Private relationalPaneField As RelationalFieldPane
        
        Private autoAddChoicesField As Boolean
        
        '''<remarks/>
        Public Property FieldArtifactTypeID() As Integer
            Get
                Return Me.fieldArtifactTypeIDField
            End Get
            Set
                Me.fieldArtifactTypeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayName() As String
            Get
                Return Me.displayNameField
            End Get
            Set
                Me.displayNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldTypeID() As Integer
            Get
                Return Me.fieldTypeIDField
            End Get
            Set
                Me.fieldTypeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldType() As FieldType
            Get
                Return Me.fieldTypeField
            End Get
            Set
                Me.fieldTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldCategoryID() As Integer
            Get
                Return Me.fieldCategoryIDField
            End Get
            Set
                Me.fieldCategoryIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldCategory() As FieldCategory
            Get
                Return Me.fieldCategoryField
            End Get
            Set
                Me.fieldCategoryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ArtifactViewFieldID() As Integer
            Get
                Return Me.artifactViewFieldIDField
            End Get
            Set
                Me.artifactViewFieldIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodeTypeID() As System.Nullable(Of Integer)
            Get
                Return Me.codeTypeIDField
            End Get
            Set
                Me.codeTypeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MaxLength() As System.Nullable(Of Integer)
            Get
                Return Me.maxLengthField
            End Get
            Set
                Me.maxLengthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsRequired() As Boolean
            Get
                Return Me.isRequiredField
            End Get
            Set
                Me.isRequiredField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsRemovable() As Boolean
            Get
                Return Me.isRemovableField
            End Get
            Set
                Me.isRemovableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsEditable() As Boolean
            Get
                Return Me.isEditableField
            End Get
            Set
                Me.isEditableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsVisible() As Boolean
            Get
                Return Me.isVisibleField
            End Get
            Set
                Me.isVisibleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsArtifactBaseField() As Boolean
            Get
                Return Me.isArtifactBaseFieldField
            End Get
            Set
                Me.isArtifactBaseFieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TableName() As String
            Get
                Return Me.tableNameField
            End Get
            Set
                Me.tableNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ColumnName() As String
            Get
                Return Me.columnNameField
            End Get
            Set
                Me.columnNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsReadOnlyInLayout() As Boolean
            Get
                Return Me.isReadOnlyInLayoutField
            End Get
            Set
                Me.isReadOnlyInLayoutField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FilterType() As String
            Get
                Return Me.filterTypeField
            End Get
            Set
                Me.filterTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldDisplayTypeID() As Integer
            Get
                Return Me.fieldDisplayTypeIDField
            End Get
            Set
                Me.fieldDisplayTypeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Rows() As Integer
            Get
                Return Me.rowsField
            End Get
            Set
                Me.rowsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsLinked() As Boolean
            Get
                Return Me.isLinkedField
            End Get
            Set
                Me.isLinkedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FormatString() As String
            Get
                Return Me.formatStringField
            End Get
            Set
                Me.formatStringField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RepeatColumn() As System.Nullable(Of Integer)
            Get
                Return Me.repeatColumnField
            End Get
            Set
                Me.repeatColumnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property AssociativeArtifactTypeID() As System.Nullable(Of Integer)
            Get
                Return Me.associativeArtifactTypeIDField
            End Get
            Set
                Me.associativeArtifactTypeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsAvailableToAssociativeObjects() As Boolean
            Get
                Return Me.isAvailableToAssociativeObjectsField
            End Get
            Set
                Me.isAvailableToAssociativeObjectsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsAvailableInChoiceTree() As Boolean
            Get
                Return Me.isAvailableInChoiceTreeField
            End Get
            Set
                Me.isAvailableInChoiceTreeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsGroupByEnabled() As Boolean
            Get
                Return Me.isGroupByEnabledField
            End Get
            Set
                Me.isGroupByEnabledField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsIndexEnabled() As Boolean
            Get
                Return Me.isIndexEnabledField
            End Get
            Set
                Me.isIndexEnabledField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayValueTrue() As String
            Get
                Return Me.displayValueTrueField
            End Get
            Set
                Me.displayValueTrueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayValueFalse() As String
            Get
                Return Me.displayValueFalseField
            End Get
            Set
                Me.displayValueFalseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Width() As String
            Get
                Return Me.widthField
            End Get
            Set
                Me.widthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Wrapping() As Boolean
            Get
                Return Me.wrappingField
            End Get
            Set
                Me.wrappingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LinkLayoutArtifactID() As Integer
            Get
                Return Me.linkLayoutArtifactIDField
            End Get
            Set
                Me.linkLayoutArtifactIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NameValue() As String
            Get
                Return Me.nameValueField
            End Get
            Set
                Me.nameValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LinkType() As Boolean
            Get
                Return Me.linkTypeField
            End Get
            Set
                Me.linkTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UseUnicodeEncoding() As Boolean
            Get
                Return Me.useUnicodeEncodingField
            End Get
            Set
                Me.useUnicodeEncodingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AllowHtml() As Boolean
            Get
                Return Me.allowHtmlField
            End Get
            Set
                Me.allowHtmlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsSortable() As Boolean
            Get
                Return Me.isSortableField
            End Get
            Set
                Me.isSortableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FriendlyName() As String
            Get
                Return Me.friendlyNameField
            End Get
            Set
                Me.friendlyNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ImportBehavior() As System.Nullable(Of ImportBehaviorChoice)
            Get
                Return Me.importBehaviorField
            End Get
            Set
                Me.importBehaviorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EnableDataGrid() As Boolean
            Get
                Return Me.enableDataGridField
            End Get
            Set
                Me.enableDataGridField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property OverlayBehavior() As System.Nullable(Of Boolean)
            Get
                Return Me.overlayBehaviorField
            End Get
            Set
                Me.overlayBehaviorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RelationalIndexViewArtifactID() As System.Nullable(Of Integer)
            Get
                Return Me.relationalIndexViewArtifactIDField
            End Get
            Set
                Me.relationalIndexViewArtifactIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObjectsFieldArgs() As ObjectsFieldParameters
            Get
                Return Me.objectsFieldArgsField
            End Get
            Set
                Me.objectsFieldArgsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AllowGroupBy() As Boolean
            Get
                Return Me.allowGroupByField
            End Get
            Set
                Me.allowGroupByField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AllowPivot() As Boolean
            Get
                Return Me.allowPivotField
            End Get
            Set
                Me.allowPivotField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PopupPickerView() As System.Nullable(Of Integer)
            Get
                Return Me.popupPickerViewField
            End Get
            Set
                Me.popupPickerViewField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FieldTreeView() As System.Nullable(Of Integer)
            Get
                Return Me.fieldTreeViewField
            End Get
            Set
                Me.fieldTreeViewField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property KeyboardShortcut() As KeyboardShortcut
            Get
                Return Me.keyboardShortcutField
            End Get
            Set
                Me.keyboardShortcutField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AvailableInViewer() As Boolean
            Get
                Return Me.availableInViewerField
            End Get
            Set
                Me.availableInViewerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RelativityApplications() As Integer()
            Get
                Return Me.relativityApplicationsField
            End Get
            Set
                Me.relativityApplicationsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RelationalPane() As RelationalFieldPane
            Get
                Return Me.relationalPaneField
            End Get
            Set
                Me.relationalPaneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AutoAddChoices() As Boolean
            Get
                Return Me.autoAddChoicesField
            End Get
            Set
                Me.autoAddChoicesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/FieldManager")>  _
    Public Enum FieldType
        
        '''<remarks/>
        Empty
        
        '''<remarks/>
        Varchar
        
        '''<remarks/>
        [Integer]
        
        '''<remarks/>
        [Date]
        
        '''<remarks/>
        [Boolean]
        
        '''<remarks/>
        Text
        
        '''<remarks/>
        Code
        
        '''<remarks/>
        [Decimal]
        
        '''<remarks/>
        Currency
        
        '''<remarks/>
        MultiCode
        
        '''<remarks/>
        File
        
        '''<remarks/>
        [Object]
        
        '''<remarks/>
        User
        
        '''<remarks/>
        LayoutText
        
        '''<remarks/>
        Objects
        
        '''<remarks/>
        OffTableText
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/FieldManager")>  _
    Public Enum FieldCategory
        
        '''<remarks/>
        Generic
        
        '''<remarks/>
        FullText
        
        '''<remarks/>
        Identifier
        
        '''<remarks/>
        Reflected
        
        '''<remarks/>
        Comments
        
        '''<remarks/>
        Relational
        
        '''<remarks/>
        ProductionMarker
        
        '''<remarks/>
        AutoCreate
        
        '''<remarks/>
        FileSize
        
        '''<remarks/>
        FolderName
        
        '''<remarks/>
        FileInfo
        
        '''<remarks/>
        ParentArtifact
        
        '''<remarks/>
        MarkupSetMarker
        
        '''<remarks/>
        GenericSystem
        
        '''<remarks/>
        MultiReflected
        
        '''<remarks/>
        Batch
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/FieldManager")>  _
    Partial Public Class RelationalFieldPane
        
        Private paneOrderField As Integer
        
        Private iconFilenameField As String
        
        Private columnNameField As String
        
        Private fieldArtifactIDField As Integer
        
        Private relationalViewArtifactIDField As Integer
        
        Private headerTextField As String
        
        Private iconFileDataField() As Byte
        
        Private paneIDField As Integer
        
        '''<remarks/>
        Public Property PaneOrder() As Integer
            Get
                Return Me.paneOrderField
            End Get
            Set
                Me.paneOrderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IconFilename() As String
            Get
                Return Me.iconFilenameField
            End Get
            Set
                Me.iconFilenameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ColumnName() As String
            Get
                Return Me.columnNameField
            End Get
            Set
                Me.columnNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldArtifactID() As Integer
            Get
                Return Me.fieldArtifactIDField
            End Get
            Set
                Me.fieldArtifactIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RelationalViewArtifactID() As Integer
            Get
                Return Me.relationalViewArtifactIDField
            End Get
            Set
                Me.relationalViewArtifactIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HeaderText() As String
            Get
                Return Me.headerTextField
            End Get
            Set
                Me.headerTextField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property IconFileData() As Byte()
            Get
                Return Me.iconFileDataField
            End Get
            Set
                Me.iconFileDataField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PaneID() As Integer
            Get
                Return Me.paneIDField
            End Get
            Set
                Me.paneIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/FieldManager")>  _
    Partial Public Class KeyboardShortcut
        
        Private idField As Integer
        
        Private shiftField As Boolean
        
        Private ctrlField As Boolean
        
        Private altField As Boolean
        
        Private keyField As Integer
        
        '''<remarks/>
        Public Property Id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shift() As Boolean
            Get
                Return Me.shiftField
            End Get
            Set
                Me.shiftField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ctrl() As Boolean
            Get
                Return Me.ctrlField
            End Get
            Set
                Me.ctrlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Alt() As Boolean
            Get
                Return Me.altField
            End Get
            Set
                Me.altField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Key() As Integer
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/FieldManager")>  _
    Partial Public Class ObjectsFieldParameters
        
        Private siblingFieldNameField As String
        
        Private fieldSchemaColumnNameField As String
        
        Private siblingFieldSchemaColumnNameField As String
        
        Private relationalTableSchemaNameField As String
        
        Private createForeignKeysField As Boolean
        
        '''<remarks/>
        Public Property SiblingFieldName() As String
            Get
                Return Me.siblingFieldNameField
            End Get
            Set
                Me.siblingFieldNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldSchemaColumnName() As String
            Get
                Return Me.fieldSchemaColumnNameField
            End Get
            Set
                Me.fieldSchemaColumnNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SiblingFieldSchemaColumnName() As String
            Get
                Return Me.siblingFieldSchemaColumnNameField
            End Get
            Set
                Me.siblingFieldSchemaColumnNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RelationalTableSchemaName() As String
            Get
                Return Me.relationalTableSchemaNameField
            End Get
            Set
                Me.relationalTableSchemaNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreateForeignKeys() As Boolean
            Get
                Return Me.createForeignKeysField
            End Get
            Set
                Me.createForeignKeysField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(Field)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/FieldManager")>  _
    Partial Public Class Artifact
        
        Private artifactIDField As Integer
        
        Private artifactTypeIDField As Integer
        
        Private parentArtifactIDField As System.Nullable(Of Integer)
        
        Private containerIDField As System.Nullable(Of Integer)
        
        Private accessControlListIDField As Integer
        
        Private accessControlListIsInheritedField As Boolean
        
        Private keywordsField As String
        
        Private notesField As String
        
        Private textIdentifierField As String
        
        Private lastModifiedOnField As Date
        
        Private lastModifiedByField As Integer
        
        Private createdByField As Integer
        
        Private createdOnField As Date
        
        Private deleteFlagField As Boolean
        
        Private guidsField() As System.Guid
        
        '''<remarks/>
        Public Property ArtifactID() As Integer
            Get
                Return Me.artifactIDField
            End Get
            Set
                Me.artifactIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ArtifactTypeID() As Integer
            Get
                Return Me.artifactTypeIDField
            End Get
            Set
                Me.artifactTypeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ParentArtifactID() As System.Nullable(Of Integer)
            Get
                Return Me.parentArtifactIDField
            End Get
            Set
                Me.parentArtifactIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ContainerID() As System.Nullable(Of Integer)
            Get
                Return Me.containerIDField
            End Get
            Set
                Me.containerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccessControlListID() As Integer
            Get
                Return Me.accessControlListIDField
            End Get
            Set
                Me.accessControlListIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccessControlListIsInherited() As Boolean
            Get
                Return Me.accessControlListIsInheritedField
            End Get
            Set
                Me.accessControlListIsInheritedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Keywords() As String
            Get
                Return Me.keywordsField
            End Get
            Set
                Me.keywordsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Notes() As String
            Get
                Return Me.notesField
            End Get
            Set
                Me.notesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TextIdentifier() As String
            Get
                Return Me.textIdentifierField
            End Get
            Set
                Me.textIdentifierField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastModifiedOn() As Date
            Get
                Return Me.lastModifiedOnField
            End Get
            Set
                Me.lastModifiedOnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastModifiedBy() As Integer
            Get
                Return Me.lastModifiedByField
            End Get
            Set
                Me.lastModifiedByField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedBy() As Integer
            Get
                Return Me.createdByField
            End Get
            Set
                Me.createdByField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedOn() As Date
            Get
                Return Me.createdOnField
            End Get
            Set
                Me.createdOnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DeleteFlag() As Boolean
            Get
                Return Me.deleteFlagField
            End Get
            Set
                Me.deleteFlagField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Guids() As System.Guid()
            Get
                Return Me.guidsField
            End Get
            Set
                Me.guidsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/FieldManager")>  _
    Public Enum ImportBehaviorChoice
        
        '''<remarks/>
        LeaveBlankValuesUnchanged
        
        '''<remarks/>
        ReplaceBlankValuesWithIdentifier
        
        '''<remarks/>
        ObjectFieldContainsArtifactId
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub CreateCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub ReadCompletedEventHandler(ByVal sender As Object, ByVal e As ReadCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Field
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Field)
            End Get
        End Property
    End Class
End Namespace
