export enum EventNames {
    CREATE_ACTION_BAR = "createActionBar",
    CREATE_CONSOLE = "createConsole",
    EVENT_HANDLERS_REGISTERED = "eventHandlersRegistered",
    HYDRATE_LAYOUT = "hydrateLayout",
    HYDRATE_LAYOUT_COMPLETE = "hydrateLayoutComplete",
    ITEM_LIST_MODIFY_ACTIONS = "itemListModifyActions",
    ITEM_LIST_MODIFY_COLUMNS = "itemListModifyColumns",
    ITEM_LIST_RELOADED = "itemListReloaded",
    OVERRIDE_PICKER_DATASOURCE = "overridePickerDataSource",
    PAGE_INTERACTION = "pageInteraction",
    PAGE_LOAD_COMPLETE = "pageLoadComplete",
    PAGE_UNLOAD = "pageUnload",
    POST_DELETE = "postDelete",
    POST_OBTAIN_ADDITIONAL_DATA = "postObtainAdditionalData",
    POST_SAVE = "postSave",
    PRE_DELETE = "preDelete",
    PRE_SAVE = "preSave",
    REPLACE_DELETE = "replaceDelete",
    REPLACE_FILE_ACTIONS = "replaceFileActions",
    REPLACE_GET_NEW_OBJECT_INSTANCE = "replaceGetNewObjectInstance",
    REPLACE_OBTAIN_ADDITIONAL_DATA = "replaceObtainAdditionalData",
    REPLACE_READ = "replaceRead",
    REPLACE_READ_DELETE_DEPENDENCY_LIST = "replaceReadDeleteDependencyList",
    REPLACE_SAVE = "replaceSave",
    TRANSFORM_LAYOUT = "transformLayout",
    UPDATE_ACTION_BAR = "updateActionBar",
    UPDATE_CONSOLE = "updateConsole",
    VALIDATE_SAVE = "validateSave",
    VALIDATION = "validation"
}

