@startuml

title DocumentTransferDataReader.Read()

start 
if (Reader is open) then (true)
	if (Enumerator is null) then (true)
    	partition FetchDataToRead() {
        	partition FetchArtifactDTOs() {
            	:RelativityExporterService.RetrieveData();
                :Add artifact ids into all provided scratch tables;
            }
            
            if (Artifacts were returned) then (true)
            	:Save ids in memory for reader
                (set enumerator);
            else
            	:Close reader;
            endif
        }
    endif
    
    if (Reader has more ids in memory) then (true)
    	:Set next artifact;
        :Increment count of read entries;
    elseif (All artifacts have been retrieved 
    && stop has <b>not</b> been requested) then (true)
    	:FetchDataToRead()|
        :Recursively call Read()|
    else
    	:Close reader;
    endif
endif

	:Return true if reader is open;
end

@enduml