@startuml

title Step 3 - Custom Page Load - Workflow

start

:GetFolderPathFields;
:GetAvailableEncodings;
:Check if object type is Custodian;

partition GetWorkspaceFields {
    :CreateSynchronizer|
    :Synchronizer.GetFields();
    :Serialize and return fields;
}

partition GetSourceFields {
    :GetDataProvider|
    :DataProvider.GetFields();
    :Serialize and return fields;
}

:Check if RDO has parent;

stop

@enduml