@startuml

title RIP Agent Workflow - SyncManager


start

partition JobPreExecute {
    :Retrieve IP RDO;
    if (No Source Provider) then (true)
        :Throw Exception;
    else (false)
        :Create JobHistory RDO;
    endif
}

partition GetUnbatchedIDs {
    :Get Data Provider RDO;
    :GetDataProvider|
    :GetBatchableIds;
}

:Create SyncWorker jobs in batches;

stop

@enduml