@ECHO OFF

SET BUILDCONFIG=%1
SET DEPENDENCYVERSION=%2
SET ROOT=%~dp0..
SET BUILDPROJECT=%~dp0build.build

ECHO %BUILDCONFIG%
ECHO %VERSION%
ECHO %ROOT%
ECHO %BUILDPROJECT%

nant merge_all -buildfile:"%BUILDPROJECT%" "-D:root=%Root%" "-D:buildconfig=%BUILDCONFIG%" -nologo